spring:
  application:
    name: rndealer-eureka-zuul #在注册中心显示的名字
server:
  port: 10081 #项目运行的端口

eureka:
  client:
     service-url:
      defaultZone: http://user:123456@172.16.12.1:8888/eureka/ #注册中心的地址
#自定义路由方式    routes 下面的节点名称可以自定义，比如现在的pservice，你可以取名其他名称，path的地址，你可以自定义前缀，但是serviceId必须是你服务名的真是名称
# sensitiveHeaders: "*" 解决zuul转发的时候 session获取不到的问题
zuul:
  routes:
    pservice:
      path: /p/**
      serviceId: product
      sensitiveHeaders: "*"
    pservice2:
      path: /p1/**
      serviceId: product
      sensitiveHeaders: "*"
  retryable: true
  
ribbon:
  eureka:
    enabled: true #是否在ribbon中使用

#product是服务的名称
product:
  ribbon:
    ReadTimeout: 2000
    ConnectTimeout: 2000
    #对当前实例的重试次数
    MaxAutoRetries: 3
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 0

    
    