#服务端口配置
#测试是否用URL地址前缀 servlet.context-path 加了之后需要在访问ip:port/xcf 才能正常访问
server:
  port: 8868
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /xcf
#数据源的配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.42.128:3306/Movie?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Root-123
#    url: jdbc:mysql://172.16.20.47:3306/zhuge?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: igxecom
#    password: igxecom2019
  redis:
   host: 192.168.10.65
   port: 6379
   password: null
   timeout: 300
   database: 1
  cache:
    type: redis #设置spring的二级缓存为redis
#mybatis配置    
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xcf.mybatis.Core
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #这里打印的是mybatis返查询语句及返回数据
#logging 打印查询sql语句
logging:
  level:
   com.xcf.mybatis.Mapper: debug  # 改成你的mapper文件所在包路径
#test @canshu@
aite:
 canshu: 'SpringCloud-parent'
    